version: '3.8'

services:
  # db_master
  db_master:
    container_name: iam_pg_master
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/db/master/pgdata:/var/lib/postgresql/data
    networks:
      - iam
    env_file:
      - .env

  # pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: iam_pgadmin
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db_master
    ports:
      - 5050:80
    networks:
      - iam
    restart: always

  # rabbitmq
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ${PWD}/rabbitmq:/data
    env_file:
      - .env
    networks:
      - iam
  # redis
  redis:
    image: redis:latest
    container_name: 'iam-redis'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - iam
    volumes:
      - ${PWD}/redis:/data
  
  # iam
  iam:
    container_name: iam
    restart: always
    depends_on:
      - db_master
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile.develop
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=4000
      - NODE_ENV=development
    ports:
      - 4000:4000
    networks:
      - iam

volumes:
  postgres_data:
  rabbitmq_data:
  redis-data:
networks:
  iam:
    driver: bridge
