export const RoutingKey = {
  USER: {
    GET_USER: 'GWT_USER',
    UPDATE_USER: 'UPDATE_USER',
    CREATE_USER: 'CREATE_USER',
  },
  AUTH: {
    LOGIN: 'LOGIN',
    LOGIN_GUEST: 'LOGIN_GUEST',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
  },
};
