export enum IamChannel {
  PACKAGE_SERVICE = 'PACKAGE-SERVICE',
  PLAYER_RESOURCE_SERVICE = 'PLAYER_RESOURCE_SERVICE',
  GAME_SERVICE = 'GAME_SERVICE',
  EVENT_TOURAMENT_SERVICE = 'EVENT_TOURAMENT_SERVICE',
  CHANNEL_CMS_SERVICE = 'CHANNEL_CMS_SERVICE',
}

export enum IamMessageEvent {
  UPDATE_TOKEN_ENERGY = 'UPDATE_TOKEN_ENERGY',
  MESSAGE = 'message',
  UPDATE_PACKAGE = 'UPDATE-PACKAGE',
  UPDATE_DATA_GAME = 'UPDATE_DATA_GAME',
}
